# Generated by Django 3.2.2 on 2021-06-18 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20210618_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='building_name',
            name='num_floors',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
