# Generated by Django 3.2.2 on 2021-07-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_building_name_num_floors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
